name: cry
description: 一个Flutter组件库，参考https://github.com/cairuoyu/flutter_admin
version: 1.3.0
homepage: http://www.cairuoyu.com/
#publish_to: https://pub.dev
#publish_to: https://pub.dartlang.org

environment:
  sdk: 3.2.0
  flutter: 3.16.0

dependencies:
  flutter:
    sdk: flutter
  quiver: 3.0.0
  dio: 5.0.0
  global_configuration: 2.0.0-nullsafety.0
  intl: 0.18.1
  date_format: 2.0.2
  image_picker: 0.7.3
  image_picker_for_web: 2.0.0
  file_picker: 3.0.0
  flutter_markdown: 0.6.1
  fluttertoast: 8.0.3
  yaml: 3.1.0
  camera: 0.9.7+1
  google_ml_kit: 0.5.0
  tflite_flutter: 0.8.0
  image: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

flutter_intl:
  enabled: true
  main_locale: ar
